### ISSUE TITLE
Request: update "usage" part on the main page

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [trello/victor#56]
Becuase it doesn't show the code that uses it, and the restrictions of using it

**Comment by dlew** [comment]
I'm not going to document how to use drawables.

**Comment by AndroidDeveloperLB** [comment]
@dlew You didn't even mention there to put the files into drawable folder (and to which).
In fact, even in the sample, I don't see it in "res" folder . The SVG files are in "svg" folder instead, which is also not mentioned in the "usage" part.

Please put the needed steps to use this library, and show an SVG file. If the rest is as using drawable files, please mention it.

**Comment by dlew** [comment]
The whole first section is about where to put the files. You have to setup your own source sets, which means that there is no predefined location for SVG files. That's why the usage section shows you how to add the source set of your choosing, which in this case just happens to be `src/main/svg`.

That is demonstrated in the sample, as well as using the output drawables in XML and in code. I don't know what more you want.

Maybe you can submit a PR showing exactly what you think should be there that's not right now.

**Comment by AndroidDeveloperLB** [comment]
understood
