### ISSUE TITLE
Add support for 9-patches

### ISSUE THREAD

**Issue by dlew** [trello/victor#6]
Obviously.

**Comment by dlew** [comment]
I would love to see people's input on the best way to support 9-patches. Obviously you can't just stick a border on the SVG because during scaling it might end up being more than 1px large.

Methods I've seen others use:

1. Hidden SVG layers.
2. Companion resource that defines the 9patch.

**Comment by dlew** [comment]
My latest thinking is to have two optional layers:

1. A "scalable" layer, with vertical or horizontal lines defining the stretchable areas. This would be equivalent to the left/top parts of a 9-patch.
2. A "content" layer, with a single rectangle defining where the content should go. This would be equivalent of the right/bottom parts of a 9-patch.

Both layers would have a name we could use to identify them. They would not have to be hidden since we'll just render 9-patches manually (and can hide the layer before rendering).

**Comment by redwarp** [comment]
Or an associated json (or other format file)? Expressing, in percent, the location of the different types of border? If you added a simple tool to visualize a .svg, edit the borders and export... Otherwise, you would need a tool to validate the 2 layer format anyway...

**Comment by dlew** [comment]
A companion resource would need validation, too. At least with layers you could visually see what you're doing.

**Comment by hamidp** [comment]
With layers you can easily export them to a png and run the 9patch tool to make sure it does actually work as it should.

**Comment by redwarp** [comment]
It's true. But I'm thinking as a small time developer that will create svg for personal projects (at work, we have designers to do so). Personally, I already struggle to create basic proper .svg for icons (I'm starting to work with them because, with Lollipop, you get this cool animated transition thingy between .svg). I'm pretty bad at it, and I'm not even sure what tool I should use to create them (tried a bunch of open source tools, tried Illustrator with Creative Cloud trial, etc).
So if you ask me to create a two layered properly designed .svg, I wouldn't be able to. Of course, at the office, that would not be an issue, as I would just go and ask the designer.

**Comment by dlew** [comment]
Victor is in maintenance mode, so not adding this feature anytime soon.
