### ISSUE TITLE
Gracefully handle Toolkit not found: apple.awt.CToolkit

### ISSUE THREAD

**Issue by hamidp** [trello/victor#9]
If we were to spawn a separate process using JDK 1.7 instead of Apple this should address the issue AND not require AS modification to work.

@dlew Correct?

**Comment by dlew** [comment]
Yes, that would work. That's actually what Victor was originally doing by using [the standalone Batik rasterizer](https://xmlgraphics.apache.org/batik/tools/rasterizer.html).

I switched away from the standalone Batik rasterizer because it was slower (since I couldn't batch multiple conversions into one execution). But if we wrote our own standalone solution it could execute a single time. It would probably still be slower since it has to execute separately.

Overall it seemed silly to execute a standalone Java process when we own all the code here, but there is that nastiness with JDK 1.7... :/

**Comment by hamidp** [comment]
Update -- it *seems* like disabling the in-process build in AS fixes this.

**Comment by dlew** [comment]
What does that mean exactly?

**Comment by hamidp** [comment]
@dlew 

Essentially I disabled [this](http://i.imgur.com/hf290N4.png) and setup the gradle daemon. This way, the build runs outside of AS, so I get to use the 1.6 Apple JDK with subpixel aliasing and teh build runs under 1.8.

So far, it seems to work well -- clean then rebuild had no issues.

**Comment by dlew** [comment]
Perhaps the answer, then, is to just update the README with this second possible course of action.

Well, the best would be if we could figure out how to make JDK 1.6 AWT work with Batik...

**Comment by hamidp** [comment]
I tried hard to get that to work with no success. If someone could figure that out they would be my hero forever

**Comment by benjaminVadon** [comment]
This option " in-process build " seems not to be present anymore in 1.3 preview
